
Epoch [10], val_loss: 0.1867
Epoch [20], val_loss: 0.1864
Epoch [30], val_loss: 0.1885
Epoch [40], val_loss: 0.1822
Epoch [50], val_loss: 0.1824
Epoch [60], val_loss: 0.1815
Epoch [70], val_loss: 0.1844
Epoch [80], val_loss: 0.1806
Epoch [90], val_loss: 0.1825
Exception in thread Thread-184:
Traceback (most recent call last):
  File "/home/jeffreymo572/anaconda3/envs/Kaggles/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/jeffreymo572/anaconda3/envs/Kaggles/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jeffreymo572/anaconda3/envs/Kaggles/lib/python3.8/site-packages/torch/utils/data/_utils/pin_memory.py", line 49, in _pin_memory_loop
    do_one_step()
  File "/home/jeffreymo572/anaconda3/envs/Kaggles/lib/python3.8/site-packages/torch/utils/data/_utils/pin_memory.py", line 26, in do_one_step
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/home/jeffreymo572/anaconda3/envs/Kaggles/lib/python3.8/multiprocessing/queues.py", line 116, in get
    return _ForkingPickler.loads(res)
  File "/home/jeffreymo572/anaconda3/envs/Kaggles/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 305, in rebuild_storage_fd
    fd = df.detach()
  File "/home/jeffreymo572/anaconda3/envs/Kaggles/lib/python3.8/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/home/jeffreymo572/anaconda3/envs/Kaggles/lib/python3.8/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/home/jeffreymo572/anaconda3/envs/Kaggles/lib/python3.8/multiprocessing/connection.py", line 502, in Client
    c = SocketClient(address)
  File "/home/jeffreymo572/anaconda3/envs/Kaggles/lib/python3.8/multiprocessing/connection.py", line 630, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "main.py", line 45, in <module>
    val_loss = evaluate(net, val_ds, device)
  File "/home/jeffreymo572/Kaggles/common/utils.py", line 120, in fit
    loss.backward()
  File "/home/jeffreymo572/anaconda3/envs/Kaggles/lib/python3.8/site-packages/torch/_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "/home/jeffreymo572/anaconda3/envs/Kaggles/lib/python3.8/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
KeyboardInterrupt