Traceback (most recent call last):
  File "main.py", line 36, in <module>
    history = fit(epochs, net, train_ds, val_ds, device, opt = optimizer)
  File "/home/jeffreymo572/Kaggles/common/utils.py", line 101, in fit
    wandb.log({"Evaluation result": result, "Loss": np.mean(np.array(losses))})
  File "<__array_function__ internals>", line 5, in mean
  File "/home/jeffreymo572/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 3372, in mean
    return _methods._mean(a, axis=axis, dtype=dtype,
  File "/home/jeffreymo572/.local/lib/python3.8/site-packages/numpy/core/_methods.py", line 170, in _mean
    ret = ret.dtype.type(ret / rcount)
AttributeError: 'torch.dtype' object has no attribute 'type'