Traceback (most recent call last):
  File "main.py", line 27, in <module>
    df = df[:reduction]
  File "/home/jeffreymo572/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3430, in __getitem__
    indexer = convert_to_index_sliceable(self, key)
  File "/home/jeffreymo572/.local/lib/python3.8/site-packages/pandas/core/indexing.py", line 2329, in convert_to_index_sliceable
    return idx._convert_slice_indexer(key, kind="getitem")
  File "/home/jeffreymo572/.local/lib/python3.8/site-packages/pandas/core/indexes/numeric.py", line 244, in _convert_slice_indexer
    return super()._convert_slice_indexer(key, kind=kind)
  File "/home/jeffreymo572/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3720, in _convert_slice_indexer
    self._validate_indexer("slice", key.stop, "getitem")
  File "/home/jeffreymo572/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 5719, in _validate_indexer
    raise self._invalid_indexer(form, key)
TypeError: cannot do slice indexing on RangeIndex with these indexers [8420.0] of type float